module.exports = {
  'data':
  [
    {
      'ID': 36,
      'post_author': 1,
      'post_date': '2018-09-25 08:10:00',
      'post_date_gmt': '2018-09-25 08:10:00',
      'post_content': 'a:7:{s:8:"location";a:1:{i:0;a:1:{i:0;a:3:{s:5:"param";s:4:"page";s:8:"operator";s:2:"==";s:5:"value";s:2:"40";}}}s:8:"position";s:6:"normal";s:5:"style";s:7:"default";s:15:"label_placement";s:3:"top";s:21:"instruction_placement";s:5:"label";s:14:"hide_on_screen";s:0:"";s:11:"description";s:0:"";}',
      'post_title': 'Apple Information',
      'post_excerpt': 'apple-information',
      'post_status': 'publish',
      'comment_status': 'closed',
      'ping_status': 'closed',
      'post_password': '',
      'post_name': 'group_5ba9ec9192397',
      'to_ping': '',
      'pinged': '',
      'post_modified': '2018-09-25 08:13:47',
      'post_modified_gmt': '2018-09-25 08:13:47',
      'post_content_filtered': '',
      'post_parent': 0,
      'guid': 'http://testpress.localhost/?post_type=acf-field-group&#038;p=36',
      'menu_order': 0,
      'post_type': 'acf-field-group',
      'post_mime_type': '',
      'comment_count': 0
    },
    {
      'ID': 37,
      'post_author': 1,
      'post_date': '2018-09-25 08:10:00',
      'post_date_gmt': '2018-09-25 08:10:00',
      'post_content': 'a:10:{s:4:"type";s:4:"text";s:12:"instructions";s:0:"";s:8:"required";i:0;s:17:"conditional_logic";i:0;s:7:"wrapper";a:3:{s:5:"width";s:0:"";s:5:"class";s:0:"";s:2:"id";s:0:"";}s:13:"default_value";s:0:"";s:11:"placeholder";s:0:"";s:7:"prepend";s:0:"";s:6:"append";s:0:"";s:9:"maxlength";s:0:"";}',
      'post_title': 'Location',
      'post_excerpt': 'location',
      'post_status': 'publish',
      'comment_status': 'closed',
      'ping_status': 'closed',
      'post_password': '',
      'post_name': 'field_5ba9ed275d103',
      'to_ping': '',
      'pinged': '',
      'post_modified': '2018-09-25 08:10:00',
      'post_modified_gmt': '2018-09-25 08:10:00',
      'post_content_filtered': '',
      'post_parent': 36,
      'guid': 'http://testpress.localhost/?post_type=acf-field&p=37',
      'menu_order': 0,
      'post_type': 'acf-field',
      'post_mime_type': '',
      'comment_count': 0
    },
    {
      'ID': 38,
      'post_author': 1,
      'post_date': '2018-09-25 08:10:52',
      'post_date_gmt': '2018-09-25 08:10:52',
      'post_content': 'a:7:{s:8:"location";a:1:{i:0;a:1:{i:0;a:3:{s:5:"param";s:4:"page";s:8:"operator";s:2:"==";s:5:"value";s:2:"40";}}}s:8:"position";s:6:"normal";s:5:"style";s:7:"default";s:15:"label_placement";s:3:"top";s:21:"instruction_placement";s:5:"label";s:14:"hide_on_screen";s:0:"";s:11:"description";s:0:"";}',
      'post_title': 'Orange Information',
      'post_excerpt': 'orange-information',
      'post_status': 'publish',
      'comment_status': 'closed',
      'ping_status': 'closed',
      'post_password': '',
      'post_name': 'group_5ba9ed60b7d4d',
      'to_ping': '',
      'pinged': '',
      'post_modified': '2018-09-25 08:13:50',
      'post_modified_gmt': '2018-09-25 08:13:50',
      'post_content_filtered': '',
      'post_parent': 0,
      'guid': 'http://testpress.localhost/?post_type=acf-field-group&#038;p=38',
      'menu_order': 0,
      'post_type': 'acf-field-group',
      'post_mime_type': '',
      'comment_count': 0
    },
    {
      'ID': 39,
      'post_author': 1,
      'post_date': '2018-09-25 08:10:52',
      'post_date_gmt': '2018-09-25 08:10:52',
      'post_content': 'a:10:{s:4:"type";s:4:"text";s:12:"instructions";s:0:"";s:8:"required";i:0;s:17:"conditional_logic";i:0;s:7:"wrapper";a:3:{s:5:"width";s:0:"";s:5:"class";s:0:"";s:2:"id";s:0:"";}s:13:"default_value";s:0:"";s:11:"placeholder";s:0:"";s:7:"prepend";s:0:"";s:6:"append";s:0:"";s:9:"maxlength";s:0:"";}',
      'post_title': 'Locale',
      'post_excerpt': 'locale',
      'post_status': 'publish',
      'comment_status': 'closed',
      'ping_status': 'closed',
      'post_password': '',
      'post_name': 'field_5ba9ed7c84abd',
      'to_ping': '',
      'pinged': '',
      'post_modified': '2018-09-25 08:10:52',
      'post_modified_gmt': '2018-09-25 08:10:52',
      'post_content_filtered': '',
      'post_parent': 38,
      'guid': 'http://testpress.localhost/?post_type=acf-field&p=39',
      'menu_order': 0,
      'post_type': 'acf-field',
      'post_mime_type': '',
      'comment_count': 0
    },
    {
      'ID': 40,
      'post_author': 1,
      'post_date': '2018-09-25 08:13:40',
      'post_date_gmt': '2018-09-25 08:13:40',
      'post_content': '',
      'post_title': 'Landing Page',
      'post_excerpt': '',
      'post_status': 'publish',
      'comment_status': 'closed',
      'ping_status': 'closed',
      'post_password': '',
      'post_name': 'landing-page',
      'to_ping': '',
      'pinged': '',
      'post_modified': '2018-09-25 08:41:26',
      'post_modified_gmt': '2018-09-25 08:41:26',
      'post_content_filtered': '',
      'post_parent': 0,
      'guid': 'http://testpress.localhost/?page_id=40',
      'menu_order': 0,
      'post_type': 'page',
      'post_mime_type': '',
      'comment_count': 0
    },
    {
      'ID': 41,
      'post_author': 1,
      'post_date': '2018-09-25 08:13:40',
      'post_date_gmt': '2018-09-25 08:13:40',
      'post_content': '',
      'post_title': 'Landing Page',
      'post_excerpt': '',
      'post_status': 'inherit',
      'comment_status': 'closed',
      'ping_status': 'closed',
      'post_password': '',
      'post_name': '40-revision-v1',
      'to_ping': '',
      'pinged': '',
      'post_modified': '2018-09-25 08:13:40',
      'post_modified_gmt': '2018-09-25 08:13:40',
      'post_content_filtered': '',
      'post_parent': 40,
      'guid': 'http://testpress.localhost/?p=41',
      'menu_order': 0,
      'post_type': 'revision',
      'post_mime_type': '',
      'comment_count': 0
    },
    {
      'ID': 42,
      'post_author': 1,
      'post_date': '2018-09-25 08:41:26',
      'post_date_gmt': '2018-09-25 08:41:26',
      'post_content': '',
      'post_title': 'Landing Page',
      'post_excerpt': '',
      'post_status': 'inherit',
      'comment_status': 'closed',
      'ping_status': 'closed',
      'post_password': '',
      'post_name': '40-revision-v1',
      'to_ping': '',
      'pinged': '',
      'post_modified': '2018-09-25 08:41:26',
      'post_modified_gmt': '2018-09-25 08:41:26',
      'post_content_filtered': '',
      'post_parent': 40,
      'guid': 'http://testpress.localhost/?p=42',
      'menu_order': 0,
      'post_type': 'revision',
      'post_mime_type': '',
      'comment_count': 0
    }
  ]
}
