module.exports = [
  {"id":1,"post_author":1,"post_title":"Hello world!","post_content":"Welcome to WordPress. This is your first post. Edit or delete it, then start writing!","post_excerpt":"","post_status":"publish","post_type":"post","post_name":"hello-world","post_date":"2018-06-22T05:53:11.000Z","post_parent":0,"menu_order":0,"guid":"http://acfql.backend.localhost/?p=1"},
  {"id":2,"post_author":1,"post_title":"Sample Page","post_content":"This is an example page. It's different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:\n\n<blockquote>Hi there! I'm a bike messenger by day, aspiring actor by night, and this is my website. I live in Los Angeles, have a great dog named Jack, and I like pi&#241;a coladas. (And gettin' caught in the rain.)</blockquote>\n\n...or something like this:\n\n<blockquote>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</blockquote>\n\nAs a new WordPress user, you should go to <a href=\"http://acfql.backend.localhost/wp-admin/\">your dashboard</a> to delete this page and create new pages for your content. Have fun!","post_excerpt":"","post_status":"publish","post_type":"page","post_name":"sample-page","post_date":"2018-06-22T05:53:11.000Z","post_parent":0,"menu_order":0,"guid":"http://acfql.backend.localhost/?page_id=2"},
  {"id":3,"post_author":1,"post_title":"Auto Draft","post_content":"","post_excerpt":"","post_status":"auto-draft","post_type":"post","post_name":"","post_date":"2018-06-22T05:53:26.000Z","post_parent":0,"menu_order":0,"guid":"http://acfql.backend.localhost/?p=3"},
  {"id":7,"post_author":1,"post_title":"Apple Information","post_content":"a:7:{s:8:\"location\";a:1:{i:0;a:1:{i:0;a:3:{s:5:\"param\";s:9:\"post_type\";s:8:\"operator\";s:2:\"==\";s:5:\"value\";s:8:\"wp_apple\";}}}s:8:\"position\";s:15:\"acf_after_title\";s:5:\"style\";s:7:\"default\";s:15:\"label_placement\";s:3:\"top\";s:21:\"instruction_placement\";s:5:\"label\";s:14:\"hide_on_screen\";s:0:\"\";s:11:\"description\";s:0:\"\";}","post_excerpt":"apple-information","post_status":"publish","post_type":"acf-field-group","post_name":"group_5b2c911d6167e","post_date":"2018-06-22T06:04:50.000Z","post_parent":0,"menu_order":0,"guid":"http://acfql.backend.localhost/?post_type=acf-field-group&#038;p=7"},
  {"id":8,"post_author":1,"post_title":"Cultivar","post_content":"a:10:{s:4:\"type\";s:4:\"text\";s:12:\"instructions\";s:17:\"The type of apple\";s:8:\"required\";i:0;s:17:\"conditional_logic\";i:0;s:7:\"wrapper\";a:3:{s:5:\"width\";s:0:\"\";s:5:\"class\";s:0:\"\";s:2:\"id\";s:0:\"\";}s:13:\"default_value\";s:0:\"\";s:11:\"placeholder\";s:0:\"\";s:7:\"prepend\";s:0:\"\";s:6:\"append\";s:0:\"\";s:9:\"maxlength\";s:0:\"\";}","post_excerpt":"cultivar","post_status":"publish","post_type":"acf-field","post_name":"field_5b2c912eb56a7","post_date":"2018-06-22T06:04:50.000Z","post_parent":7,"menu_order":0,"guid":"http://acfql.backend.localhost/?post_type=acf-field&p=8"},
  {"id":9,"post_author":1,"post_title":"Royal Gala","post_content":"","post_excerpt":"","post_status":"publish","post_type":"wp_apple","post_name":"royal-gala","post_date":"2018-06-23T11:07:38.000Z","post_parent":0,"menu_order":0,"guid":"http://acfql.backend.localhost/?post_type=wp_apple&#038;p=9"},
  {"id":10,"post_author":1,"post_title":"Apple Image","post_content":"a:15:{s:4:\"type\";s:5:\"image\";s:12:\"instructions\";s:21:\"An image of the apple\";s:8:\"required\";i:0;s:17:\"conditional_logic\";i:0;s:7:\"wrapper\";a:3:{s:5:\"width\";s:0:\"\";s:5:\"class\";s:0:\"\";s:2:\"id\";s:0:\"\";}s:13:\"return_format\";s:5:\"array\";s:12:\"preview_size\";s:9:\"thumbnail\";s:7:\"library\";s:3:\"all\";s:9:\"min_width\";s:0:\"\";s:10:\"min_height\";s:0:\"\";s:8:\"min_size\";s:0:\"\";s:9:\"max_width\";s:0:\"\";s:10:\"max_height\";s:0:\"\";s:8:\"max_size\";s:0:\"\";s:10:\"mime_types\";s:0:\"\";}","post_excerpt":"apple_image","post_status":"publish","post_type":"acf-field","post_name":"field_5b2ef268f9356","post_date":"2018-06-24T01:24:15.000Z","post_parent":7,"menu_order":1,"guid":"http://acfql.backend.localhost/?post_type=acf-field&p=10"},
  {"id":11,"post_author":1,"post_title":"Apple Locations","post_content":"a:10:{s:4:\"type\";s:8:\"repeater\";s:12:\"instructions\";s:30:\"Locations that the apple grows\";s:8:\"required\";i:0;s:17:\"conditional_logic\";i:0;s:7:\"wrapper\";a:3:{s:5:\"width\";s:0:\"\";s:5:\"class\";s:0:\"\";s:2:\"id\";s:0:\"\";}s:9:\"collapsed\";s:0:\"\";s:3:\"min\";s:0:\"\";s:3:\"max\";s:0:\"\";s:6:\"layout\";s:5:\"table\";s:12:\"button_label\";s:0:\"\";}","post_excerpt":"apple_locations","post_status":"publish","post_type":"acf-field","post_name":"field_5b2ef28af9357","post_date":"2018-06-24T01:24:15.000Z","post_parent":7,"menu_order":2,"guid":"http://acfql.backend.localhost/?post_type=acf-field&p=11"},
  {"id":12,"post_author":1,"post_title":"Location","post_content":"a:10:{s:4:\"type\";s:4:\"text\";s:12:\"instructions\";s:0:\"\";s:8:\"required\";i:0;s:17:\"conditional_logic\";i:0;s:7:\"wrapper\";a:3:{s:5:\"width\";s:0:\"\";s:5:\"class\";s:0:\"\";s:2:\"id\";s:0:\"\";}s:13:\"default_value\";s:0:\"\";s:11:\"placeholder\";s:0:\"\";s:7:\"prepend\";s:0:\"\";s:6:\"append\";s:0:\"\";s:9:\"maxlength\";s:0:\"\";}","post_excerpt":"location","post_status":"publish","post_type":"acf-field","post_name":"field_5b2ef2abf9358","post_date":"2018-06-24T01:24:15.000Z","post_parent":11,"menu_order":0,"guid":"http://acfql.backend.localhost/?post_type=acf-field&p=12"},
  {"id":13,"post_author":1,"post_title":"apple-royal-gala-single-resized_1024x1024","post_content":"","post_excerpt":"","post_status":"inherit","post_type":"attachment","post_name":"apple-royal-gala-single-resized_1024x1024","post_date":"2018-06-24T01:24:40.000Z","post_parent":9,"menu_order":0,"guid":"http://acfql.backend.localhost/wp-content/uploads/2018/06/apple-royal-gala-single-resized_1024x1024.jpg"}
]
  